### ISSUE TITLE
Getting an error after modifying one the files inside the `src` folder. 

### ISSUE THREAD

**Issue by JenieX** [LenAnderson/UserscriptWatcher#1]
```
groovy.lang.MissingPropertyException: No such property: context for class: sun.nio.fs.AbstractWatchKey$Event
```
* Java SE Development Kit 18.0.1.1
* Groovy 4.0.3

**Comment by LenAnderson** [comment]
You probably have to use Groovy 3. Groovy 4 was not around when this was written, and I never tested with Groovy 4.

**Comment by JenieX** [comment]
Tried it with groovy 3.0.11, but still getting the same error. Can't figure what I'm doing wrong.

**Comment by LenAnderson** [comment]
I'm using 3.0.11 as well without any issue. I just pushed an update to use the `context()` method instead of property. Maybe something changed with a newer JDK / library version.

https://code.yawk.at/java/8/sun/nio/fs/AbstractWatchKey.java#sun.nio.fs.AbstractWatchKey.Event%23context()

**Comment by JenieX** [comment]
That fixed the issue and everything is working as expected. Thank you for this neat script, will help keep my code organized.
