### ISSUE TITLE
What license does this script falls under?

### ISSUE THREAD

**Issue by JenieX** [LenAnderson/UserscriptWatcher#2]
I may share the split files (the src folder) in my MIT licensed projects, and mention your script as how I built my code.

Would it be an issue if I do that and kept the licenses of my projects as they are?

**Comment by LenAnderson** [comment]
I never bothered with a license. Feel free to do what you want with the source and any output generated by script's outputs.

**Comment by JenieX** [comment]
Awesome. Thank you very much.
